import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS Experience",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        
        
        {children}

        <footer>
          <h3 className="text-center  bg-yellow-100">
            this is my footer
          </h3>
        </footer>
      
      </body>
    </html>
  );
}
